audit_header: false
title: Phoenix Real Estate Video Blog with Monique Walker
description: >-
  Our mission at Monique Walker Team is to be your best resource for Phoenix
  real estate advice. Whether you are a buyer, seller, or investor, our team of
  professionals can answer any questions you might have about real estate. If
  you are looking to buy or sell a home, you can get all the information and the
  latest updates, tips, and tricks from The Monique Walker Team, your
  professional Phoenix Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:
show_custom_links_new_tab: false
custom_links_new_tab:
  - title:
    url:
client:
  name: Monique Walker
  title:
  license_number:
  about_markdown: >-
    Monique Walker has 21 years of experience successfully buying and selling
    homes in the Phoenix market. She knows the neighborhoods, schools, and the
    local economy. Monique and her team do all the leg work, keeping you
    up-to-date with new listings and conditions as they impact the market. They
    provide resources to home owners and buyers throughout the process and
    helped over 200 families in 2021 buy or sell a home.


    The Monique Walker Team will guide you through the complexities of buying
    and/or selling a house, eliminating hassles and stress. With an average
    list-to-sale price of 103% as well as over 3000 transactions sold, the
    Monique Walker team will show you why performance outsells promises.
  brand: Monique Walker Team
  brokerage: RE/MAX Excalibur
  market: Phoenix
  address: '8510 E. Shea #100 Scottsdale, AZ 85260'
  phone: 602-413-8195
  phone_type:
  phone2:
  phone2_type:
  email: Monique@MoniqueSells.com
  url: https://www.moniquesells.com
CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: http://www.phoenix-house-value.com/
  second_CTA_text: Home Search
  second_CTA_URL: http://www.moniquesells.com/properties/#/
sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: What’s Your Phoenix Home Worth?
    CTA_text: >-
      Are you thinking of selling your home or interested in learning about home
      prices in your neighborhood? We can help you.
    CTA_link_text: Free Home Value Report
    CTA_url: http://www.phoenix-house-value.com/
second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/002.jpg
    CTA_title2: Looking for a Phoenix Home?
    CTA_text2: Search the entire MLS for your Phoenix home.
    CTA_link_text2: Search the MLS
    CTA_url2: http://www.moniquesells.com/properties/#/
lender:
  show_section:
  header_text: Local Lender
  headshot_path: /uploads/kennan.jpg
  logo_path: /img/lender-logo.png
  name: Jonathon Keenan
  license_number:
  company: Bay Equity Home Loans
  company_license_number:
  phone: 602.714.1803
  email: jkeenan@bayeq.com
  url:
socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/MoniqueWalkerSells/
  linkedin_url: https://www.linkedin.com/in/moniquewalkersells
  youtube_url: https://www.youtube.com/channel/UCkcX2e8dZyZIjT2yqhjfQhA
  twitter_url: https://twitter.com/MoniqueSellsAZ
  instagram_url:
  pinterest_url:
  zillow_url: http://www.zillow.com/profile/moniquewalkersells/
  trulia_url: >-
    http://www.trulia.com/profile/monique-walker-agent-phoenix-az-11315847/overview
  yelp_url: http://www.yelp.com/biz/monique-walker-re-max-excalibur-scottsdale
  podcast_url:
podcast:
  title: Phoenix Real Estate Podcast with Monique Walker
  categories: Education
  image: /img/podcast.jpg
  subtitle: >-
    Learn all the tips, tricks and more for buyers and sellers in the Phoenix
    Area Real Estate Market
  description: >-
    If you are looking to buy or sell a home, get all the information and the
    latest updates, tips, and tricks from Monique Walker Team - your
    professional Phoenix Real Estate Agents.
  keywords: >-
    Real Estate for sale, Real Estate agents, top real estate agents, local real
    estate agents, find a real estate agent, houses for sale in Phoenix, home
    selling tips, home for sale, home buying, home buying process, property
    finder, property search, property, real estate market, estate agent,
    realestate, real estate listings, buying a house, homes for sale, mls, home
    buyer
  author: Monique Walker
images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 60
  hero_text: Phoenix Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
  post_cta_image: /img/home-value.jpg
  post_cta_image2: /img/home-search.jpg
site_colors:
  brand_color: '#003968'
  theme_color: '#003968'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'
header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: black
buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: rgba(0, 0, 0, 0)
  secondary_button_text_color: '#ffffff'
